<?php

// all possible options will be stored
$config = array();

// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
$config['app_key'] = 'EnglonProx';

// a secret key to be used during encryption
$config['encryption_key'] = 'kC/CXSHMacMktphDo6I2iWjQPzyyl6Y8zV1MIanbx94=';

// URL running the proxy app
$config['app_url'] = 'https://'.$_SERVER["SERVER_NAME"].'/p/';

/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
1 - Base64 encoding only, people can hotlink to your proxy
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/

$config['url_mode'] = 1;

// Disabling PHP session for
// - performance reasons
// - avoids sending additional headers (Expires, Cache-Control, Pragma) that get attached when you run session_start()
// set it to 'true' when using url_mode=3
$config['session_enable'] = false;

// By default: PHP will append "X-Powered-By" to your own list of headers
$config['expose_php'] = false;

// plugins to load - plugins will be loaded in this exact order as in array
$config['plugins'] = array(
    'HeaderRewrite',
    'Stream',
    // ^^ do not disable any of the plugins above
    'Cookie',
    'Proxify',
    'UrlForm',
    // site specific plugins below
    'Youtube',
    'DailyMotion',
    'Twitter'
);

// additional curl options to go with each request
$config['curl'] = array(
    // CURLOPT_PROXY => '',
    // CURLOPT_CONNECTTIMEOUT => 5
);

$config['replace_title'] = 'Untitled document - Google Docs';

//$config['error_redirect'] = "https://englon.uk/swr?e={error_msg}";
//$config['index_redirect'] = 'https://englon.uk/p/';

$config['replace_icon'] = '../favicon.ico';

// this better be here other Config::load fails
return $config;
